cd assimpBuild
cmake -G "Visual Studio 16 2019" -A Win32 -DLIBRARY_SUFFIX="" -DASSIMP_NO_EXPORT=ON -DASSIMP_BUILD_ASSIMP_TOOLS=OFF -DASSIMP_BUILD_TESTS=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX="install" ../assimp
exit /b 0
